name: sbc_nas_interface
description: A Dart project for SBC-NAS Interface

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  flutter_lints: ^6.0.0
  gauge_indicator: ^0.4.3
  http: ^1.1.0
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env